import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, Easing, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Switch, Text, View } from 'react-native';

const palette = { canvas: '#FCF8F2', ink: '#202326', muted: '#71716D', line: '#DDD8CF', peach: '#F8DDD0', blue: '#DCE9F0', sage: '#DDE8D8', ochre: '#E7B86B', blush: '#F2E4E0', white: '#FFFCF7' };
const rituals = {
  overwhelmed: { title: 'Come back to centre', subtitle: 'A grounding pause for when everything feels like too much.', accent: palette.blue, art: 'breath' },
  tense: { title: 'Soften the edges', subtitle: 'Release held tension and let your body settle.', accent: palette.peach, art: 'body' },
  scattered: { title: 'One thing at a time', subtitle: 'Find your next clear step with a quiet reset.', accent: palette.sage, art: 'hands' },
  tired: { title: 'Rest between moments', subtitle: 'A gentle transition for an overfull day.', accent: palette.blush, art: 'moon' },
  pause: { title: 'A small return', subtitle: 'Nothing to fix. Just five minutes to be here.', accent: '#F2E8D2', art: 'body' },
};
const collections = [
  { title: 'Reset now', note: 'For the in-between moments', color: palette.blue, key: 'overwhelmed', art: 'breath' },
  { title: 'Wind down', note: 'Settle into your evening', color: palette.blush, key: 'tired', art: 'moon' },
  { title: 'Return to focus', note: 'Clear a little space', color: palette.sage, key: 'scattered', art: 'hands' },
];

function Button({ label, onPress, kind = 'dark' }) { return <Pressable onPress={onPress} style={[styles.button, kind === 'light' && styles.buttonLight]}><Text style={[styles.buttonText, kind === 'light' && styles.buttonTextLight]}>{label}</Text></Pressable>; }
function BodyArt({ type = 'body', small = false, color = palette.ochre }) { return <View pointerEvents="none" style={[styles.art, small && styles.artSmall]}><View style={[styles.artBlob, { backgroundColor: color }]} /><View style={[styles.artBlobTwo, { backgroundColor: type === 'moon' ? palette.blue : palette.peach }]} />{type === 'hands' ? <><View style={[styles.handLine, styles.handOne]} /><View style={[styles.handLine, styles.handTwo]} /><View style={[styles.handLine, styles.handThree]} /><View style={[styles.artArc, styles.arcBottom]} /></> : <><View style={[styles.bodyHead, type === 'moon' && styles.moonHead]} /><View style={styles.bodyLine} /><View style={styles.bodyArmLeft} /><View style={styles.bodyArmRight} /><View style={styles.bodyLegLeft} /><View style={styles.bodyLegRight} /><View style={[styles.artArc, styles.arcTop]} />{type === 'breath' && <><View style={styles.breathRing} /><View style={styles.breathRingTwo} /></>}</>}</View>; }
function BreathingArt({ type = 'breath', small = false, color = palette.ochre }) {
  const breath = useRef(new Animated.Value(0)).current;
  useEffect(() => { const animation = Animated.loop(Animated.sequence([Animated.timing(breath, { toValue: 1, duration: 3100, easing: Easing.inOut(Easing.sin), useNativeDriver: true }), Animated.timing(breath, { toValue: 0, duration: 3100, easing: Easing.inOut(Easing.sin), useNativeDriver: true })])); animation.start(); return () => animation.stop(); }, [breath]);
  const scale = breath.interpolate({ inputRange: [0, 1], outputRange: [0.93, 1.07] }); const opacity = breath.interpolate({ inputRange: [0, 1], outputRange: [0.66, 1] });
  return <Animated.View style={{ transform: [{ scale }], opacity }}><BodyArt type={type} small={small} color={color} /></Animated.View>;
}
function PreparingRitual() {
  const spin = useRef(new Animated.Value(0)).current;
  useEffect(() => { const animation = Animated.loop(Animated.timing(spin, { toValue: 1, duration: 1200, easing: Easing.linear, useNativeDriver: true })); animation.start(); return () => animation.stop(); }, [spin]);
  const rotate = spin.interpolate({ inputRange: [0, 1], outputRange: ['0deg', '360deg'] });
  return <SafeAreaView style={styles.loaderScreen}><StatusBar barStyle="dark-content" /><Animated.View style={[styles.loaderOrbit, { transform: [{ rotate }] }]}><View style={styles.loaderDot} /></Animated.View><Text style={styles.loaderTitle}>Arriving here.</Text><Text style={styles.loaderText}>Take one slow breath while we prepare your ritual.</Text></SafeAreaView>;
}
function Doodle({ variant = 'flower' }) { return <Text style={styles.doodle}>{variant === 'flower' ? '✦' : '⌁'}</Text>; }
function Choice({ label, selected, onPress, color = palette.peach }) { return <Pressable onPress={onPress} style={[styles.choice, selected && { backgroundColor: color, borderColor: palette.ink }]}><Text style={[styles.choiceText, selected && styles.choiceTextSelected]}>{label}</Text><Text style={styles.choiceArrow}>↗</Text></Pressable>; }
function Header({ back, title }) { return <View style={styles.header}><Pressable onPress={back} hitSlop={12}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerBrand}>{title || 'inner talk'}</Text><View style={styles.headerSpace} /></View>; }
function Screen({ children, onBack, title }) { return <SafeAreaView style={styles.app}><StatusBar barStyle="dark-content" /><Header back={onBack} title={title} /><View style={styles.screen}>{children}</View></SafeAreaView>; }

export default function App() {
  const [screen, setScreen] = useState('welcome'); const [intent, setIntent] = useState('Reset'); const [state, setState] = useState('pause'); const [pendingRitual, setPendingRitual] = useState('pause'); const [completed, setCompleted] = useState(3); const [lastFeeling, setLastFeeling] = useState(null); const [reminders, setReminders] = useState(true); const current = useMemo(() => rituals[state], [state]);
  useEffect(() => { if (screen !== 'loading') return undefined; const timer = setTimeout(() => { setState(pendingRitual); setScreen('player'); }, 900); return () => clearTimeout(timer); }, [screen, pendingRitual]);
  const beginRitual = (key = state) => { setPendingRitual(key); setScreen('loading'); }; const completeCheckin = feeling => { setLastFeeling(feeling); setCompleted(value => value + 1); setScreen('home'); };
  if (screen === 'welcome') return <SafeAreaView style={styles.welcome}><StatusBar barStyle="dark-content" /><View style={styles.welcomeTop}><Text style={styles.logoMark}>◌</Text><Text style={styles.brandLight}>INNER TALK</Text></View><View style={styles.welcomeArt}><BreathingArt type="body" color={palette.ochre} /><Doodle /><View style={styles.welcomeDot} /></View><View style={styles.welcomeBottom}><Text style={styles.display}>Find a softer{`\n`}way back.</Text><Text style={styles.intro}>Five-minute rituals for the moments you need to slow down, feel, and begin again.</Text><Button label="Begin your pause" onPress={() => setScreen('intention')} /><Text style={styles.legal}>A gentle space to check in. Not therapy.</Text></View></SafeAreaView>;
  if (screen === 'intention') return <Screen onBack={() => setScreen('welcome')} title="Your intention"><Text style={styles.displaySmall}>What would feel{`\n`}supportive today?</Text><Text style={styles.bodyText}>You can change this any time. For now, choose the feeling you want more of.</Text><View style={styles.choiceStack}>{['Reset', 'Unwind', 'Focus', 'Sleep better'].map((item, index) => <Choice key={item} label={item} selected={intent === item} color={[palette.peach, palette.blue, palette.sage, palette.blush][index]} onPress={() => setIntent(item)} />)}</View><View style={styles.screenBottom}><Button label="Continue" onPress={() => setScreen('reminder')} /></View></Screen>;
  if (screen === 'reminder') return <Screen onBack={() => setScreen('intention')} title="Daily rhythm"><View style={styles.reminderArt}><BodyArt type="breath" small color={palette.ochre} /></View><Text style={styles.displaySmall}>Make room for{`\n`}a little you-time.</Text><Text style={styles.bodyText}>A small daily moment can become a place to land.</Text><View style={styles.reminderCard}><View><Text style={styles.cardEyebrow}>DAILY PAUSE</Text><Text style={styles.cardTitle}>5:30 PM · after work</Text></View><Switch value={reminders} onValueChange={setReminders} trackColor={{ false: palette.line, true: '#4B6855' }} /></View><View style={styles.screenBottom}><Button label="Start my first ritual" onPress={() => beginRitual(intent === 'Unwind' ? 'tired' : intent === 'Focus' ? 'scattered' : 'pause')} /></View></Screen>;
  if (screen === 'loading') return <PreparingRitual />;
  if (screen === 'player') return <SafeAreaView style={[styles.player, { backgroundColor: current.accent }]}><StatusBar barStyle="dark-content" /><View style={styles.playerHeader}><Pressable onPress={() => setScreen('home')} hitSlop={12}><Text style={styles.close}>×</Text></Pressable><Text style={styles.playerTime}>5:00</Text></View><View style={styles.playerArt}><BreathingArt type={current.art} color={palette.ochre} /><Doodle variant="wave" /></View><View style={styles.playerCopy}><Text style={styles.cardEyebrow}>YOUR FIVE-MINUTE PAUSE</Text><Text style={styles.playerTitle}>{current.title}</Text><Text style={styles.playerSubtitle}>{current.subtitle}</Text></View><View style={styles.playerControls}><View style={styles.progressLine}><View style={styles.progressActive} /></View><Text style={styles.playerPrompt}>Let your shoulders drop. There is nowhere else to be.</Text><Button label="Complete ritual" onPress={() => setScreen('checkin')} /></View></SafeAreaView>;
  if (screen === 'checkin') return <Screen onBack={() => setScreen('player')} title="A small noticing"><View style={styles.checkinArt}><BodyArt type="breath" small color={palette.ochre} /></View><Text style={styles.displaySmall}>How do you feel{`\n`}now?</Text><Text style={styles.bodyText}>No right answer. Just notice what is here.</Text><View style={styles.choiceStack}>{['Calmer', 'Lighter', 'More present', 'About the same', 'Still overwhelmed'].map((item, index) => <Choice key={item} label={item} color={[palette.sage, palette.blue, palette.peach, palette.blush, '#EAD3D1'][index]} onPress={() => completeCheckin(item)} />)}</View><Text style={styles.support}>If you feel unsafe or in crisis, contact local emergency services or Talk Suicide Canada at 1-833-456-4566.</Text></Screen>;
  return <SafeAreaView style={styles.app}><StatusBar barStyle="dark-content" /><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>{screen === 'home' && <Home completed={completed} lastFeeling={lastFeeling} onStart={() => setScreen('state')} onCollection={beginRitual} />}{screen === 'state' && <StatePicker onBack={() => setScreen('home')} onChoose={beginRitual} />}{screen === 'explore' && <Explore onCollection={beginRitual} />}{screen === 'progress' && <Progress completed={completed} lastFeeling={lastFeeling} />}{screen === 'profile' && <Profile reminders={reminders} setReminders={setReminders} />}</ScrollView><Nav active={screen} setScreen={setScreen} /></SafeAreaView>;
}

function Home({ completed, lastFeeling, onStart, onCollection }) { return <View><View style={styles.homeHeader}><Text style={styles.homeBrand}>INNER TALK</Text><View style={styles.profileBubble}><Text>◒</Text></View></View><Text style={styles.homeGreeting}>Good evening,</Text><Text style={styles.homeTitle}>How would you{`\n`}like to feel?</Text><Pressable onPress={onStart} style={styles.featured}><View style={styles.featuredCopy}><Text style={styles.cardEyebrow}>A FIVE-MINUTE PAUSE</Text><Text style={styles.featuredTitle}>Come back{`\n`}to centre</Text><Text style={styles.featuredButton}>Begin  →</Text></View><View style={styles.featuredArt}><BodyArt type="breath" small color={palette.ochre} /></View></Pressable>{lastFeeling && <Text style={styles.returnNote}>Last time, you felt <Text style={styles.returnStrong}>{lastFeeling.toLowerCase()}</Text>.</Text>}<View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Find your moment</Text><Text style={styles.sectionLink}>See all</Text></View><View style={styles.collectionStack}>{collections.map(item => <Pressable key={item.key} onPress={() => onCollection(item.key)} style={[styles.collectionCard, { backgroundColor: item.color }]}><View><Text style={styles.collectionTitle}>{item.title}</Text><Text style={styles.collectionNote}>{item.note}</Text><Text style={styles.collectionMeta}>5 MIN · GUIDED RITUAL</Text></View><View style={styles.collectionArt}><BodyArt type={item.art} small color={palette.ochre} /></View></Pressable>)}</View><View style={styles.momentCard}><Text style={styles.momentNumber}>{completed}</Text><View><Text style={styles.momentTitle}>moments for yourself</Text><Text style={styles.momentNote}>this week. That matters.</Text></View></View></View>; }
function StatePicker({ onBack, onChoose }) { return <View><Header back={onBack} title="Start your reset" /><Text style={styles.displaySmall}>How is your body{`\n`}feeling right now?</Text><Text style={styles.bodyText}>Choose what is closest. We’ll take it from there.</Text><View style={styles.stateGrid}>{Object.entries(rituals).map(([key, ritual]) => <Pressable key={key} onPress={() => onChoose(key)} style={[styles.stateCard, { backgroundColor: ritual.accent }]}><BodyArt type={ritual.art} small color={palette.ochre} /><Text style={styles.stateTitle}>{key === 'pause' ? 'I need a pause' : `I feel ${key}`}</Text><Text style={styles.stateArrow}>↗</Text></Pressable>)}</View></View>; }
function Explore({ onCollection }) { return <View><Text style={styles.homeBrand}>INNER TALK</Text><Text style={styles.homeTitle}>A ritual for{`\n`}this moment.</Text><Text style={styles.bodyText}>Small practices that meet you exactly where you are.</Text><View style={styles.exploreStack}>{collections.map(item => <Pressable key={item.key} onPress={() => onCollection(item.key)} style={[styles.exploreCard, { backgroundColor: item.color }]}><BodyArt type={item.art} small color={palette.ochre} /><View><Text style={styles.collectionTitle}>{item.title}</Text><Text style={styles.collectionNote}>{item.note}</Text><Text style={styles.collectionMeta}>5 MINUTES</Text></View></Pressable>)}</View></View>; }
function Progress({ completed, lastFeeling }) { const days = ['M', 'T', 'W', 'T', 'F', 'S', 'S']; return <View><Text style={styles.homeBrand}>INNER TALK</Text><Text style={styles.homeTitle}>Your quiet{`\n`}return.</Text><View style={styles.progressPanel}><BodyArt type="hands" small color={palette.ochre} /><Text style={styles.progressNumber}>{completed}</Text><Text style={styles.progressTitle}>rituals completed</Text><Text style={styles.progressCopy}>You have made room for yourself {completed} times this week.</Text></View><Text style={styles.sectionTitle}>This week</Text><View style={styles.weekRow}>{days.map((day, index) => <View key={`${day}-${index}`} style={styles.weekDay}><View style={[styles.weekDot, index < Math.min(completed, 7) && styles.weekDotDone]} /><Text style={styles.weekLabel}>{day}</Text></View>)}</View>{lastFeeling && <View style={styles.reflection}><Text style={styles.cardEyebrow}>A SMALL SHIFT</Text><Text style={styles.reflectionText}>After your last ritual, you felt {lastFeeling.toLowerCase()}.</Text></View>}</View>; }
function Profile({ reminders, setReminders }) { return <View><Text style={styles.homeBrand}>INNER TALK</Text><Text style={styles.homeTitle}>Your space.</Text><View style={styles.profileArt}><BodyArt type="body" color={palette.ochre} /></View><Text style={styles.profileLabel}>RITUAL SETTINGS</Text><View style={styles.settingsGroup}><View style={styles.settingRow}><View><Text style={styles.settingTitle}>Daily pause</Text><Text style={styles.settingNote}>5:30 PM · after work</Text></View><Switch value={reminders} onValueChange={setReminders} trackColor={{ false: palette.line, true: '#4B6855' }} /></View><View style={styles.settingRow}><Text style={styles.settingTitle}>Ambient sound</Text><Text style={styles.settingValue}>Soft rain</Text></View></View><Text style={styles.profileLabel}>YOUR PRIVACY</Text><View style={styles.settingsGroup}>{['Manage your data', 'Privacy policy', 'Delete account'].map(label => <View style={styles.settingRow} key={label}><Text style={styles.settingTitle}>{label}</Text><Text style={styles.settingValue}>›</Text></View>)}</View></View>; }
function Nav({ active, setScreen }) { const items = [['home', 'Home', '⌂'], ['explore', 'Explore', '◌'], ['progress', 'Progress', '⌁'], ['profile', 'Profile', '◒']]; return <View style={styles.nav}>{items.map(([key, label, icon]) => <Pressable key={key} onPress={() => setScreen(key)} style={styles.navItem}><Text style={[styles.navIcon, active === key && styles.navActive]}>{icon}</Text><Text style={[styles.navLabel, active === key && styles.navLabelActive]}>{label}</Text></Pressable>)}</View>; }

const serif = Platform.select({ ios: 'Georgia', default: 'serif' });
const styles = StyleSheet.create({
  loaderScreen: { flex: 1, backgroundColor: palette.canvas, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 38 }, loaderOrbit: { height: 112, width: 112, borderRadius: 56, borderWidth: 1, borderColor: palette.ink, alignItems: 'center', justifyContent: 'flex-start', marginBottom: 32 }, loaderDot: { height: 15, width: 15, borderRadius: 8, backgroundColor: palette.ochre, marginTop: -8 }, loaderTitle: { fontFamily: serif, color: palette.ink, fontSize: 34, letterSpacing: -1 }, loaderText: { color: palette.muted, fontSize: 15, lineHeight: 22, textAlign: 'center', marginTop: 12 },
});
